### ISSUE TITLE
Support for SkinnedMeshRenderer?

### ISSUE THREAD

**Issue by soraryu** [Whinarn/UnityMeshSimplifier#11]
That's a feature request - mesh simplification is cool, but would be even cooler if it kept/recalculated bone weights.

**Comment by Whinarn** [comment]
There is already support for bone weights, you would have to provide them and retrieve them (after simplification) through the [BoneWeights](https://github.com/Whinarn/UnityMeshSimplifier/blob/master/Scripts/MeshSimplifier.cs#L528) property.

If you use Initialize with a mesh and ToMesh it should be handled for you.

Perhaps your issue is with the bindposes not being preserved?
Could you try what I mention in this issue? https://github.com/Whinarn/UnityMeshSimplifier/issues/4#issuecomment-386463959
