### ISSUE TITLE
Dll exist?

### ISSUE THREAD

**Issue by seghier** [Whinarn/UnityMeshSimplifier#71]
Hello is there a package or dll library to use it in other softwares?

**Comment by Whinarn** [comment]
Hi @seghier!

Unfortunately, this package is only for Unity. You would either have to convert it to a .NET project and replace the Unity references, or find another library.

Before UnityMeshSimplifier, I had another project that worked with both Unity and regular .NET applications called MeshDecimator. It was archived in 2020, so it hasn't received the same updates. But if you are still interested to have a look, you can find it here: https://github.com/Whinarn/MeshDecimator

My recommendation would be to find another library on NuGet. But I understand that it might be difficult to find something that's free. Otherwise you have your options above.

I hope this helps. Good luck on your project!

**Comment by seghier** [comment]
Thank you @Whinarn 
Yes i already used your old project which is excellent

https://github.com/seghierk/G4Library
